Merging submission to master for ICML appendix submission
chandar-lab/Lifelong-Hanabi pull request #5
Opened 2021-02-09 19:55 UTC by hnekoeiq

2021-02-10 18:45 UTC, dapatil211 requested changes
Comments:
- need requirements.txt
- delete other branches
- A lot of the stuff in the repo would become much clearer if you added docstrings for class/functions explaining their purpose and parameters used
- There are a few sections I couldn't add inline comments because there were no changes there, so I commented close to them. Mostly, they involve removing commented code

2021-03-03 15:51 UTC, chavezrodz requested changes

2021-03-04 15:08 UTC, chavezrodz approved these changes

2021-03-04 16:16 UTC, dapatil211 approved these changes
Final comments:
- Maybe rename misc folder to something more precise, like "results" or something 
- Should hanabi_learning_environment be in third_party?
- Before making public, please delete the extra branch
- I don't see you using pyhanabi/r2d2.py anywhere. Maybe I missed it, but if not, you should probably delete it.
- setpath.py seems like a weird file in the main package. Maybe just transfer the function to one of the other util files or move the file to common_utils folder?
- maybe rename cont_multitask.py -> continual_multitask.py to be consistent with the other two runner files?

These are just suggestions, based on a limited understanding of your package, so feel free to ignore.

2021-03-04 17:49 UTC, merged